apiVersion: cache.orca.com/v1alpha1
kind: DappManifest
metadata:
  labels:
    app.kubernetes.io/name: orca
    app.kubernetes.io/managed-by: kustomize
  namespace: default
  name: dappmanifest-sample
spec:
  dappName: my-dapp
  namespace: my-dapp-system
  helm:
    releaseName: my-dapp
    chartName: podinfo
    version: ">=6.0.0"
    repoURL: https://stefanprodan.github.io/podinfo
  nodeSelector:
    type: o-du
  tolerations:
  - key: dedicated
    operator: Equal
    value: o-du
    effect: NoSchedule
