apiVersion: cache.orca.com/v1alpha1
kind: DappManifest
metadata:
  name: dapp-sample
  namespace: orca-system
spec:
  dappName: dapp-sample
  namespace: dapp-sample-system
  helm:
    releaseName: dapp-sample
    chartName: dapp-sample-app
    version: "0.1.0"
    repoURL: oci://ghcr.io/pedromartinssouza/charts
  nodeSelector:
    type: o-du
  tolerations:
  - key: dedicated
    operator: Equal
    value: o-du
    effect: NoSchedule
