replicaCount: 1

image:
  repository: ghcr.io/pedromartinssouza/orca
  pullPolicy: IfNotPresent
  # Defaults to Chart.AppVersion when empty
  tag: ""

serviceAccount:
  # Override the service account name. Defaults to the chart fullname.
  name: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

leaderElection:
  enabled: true
